spring:
  application:
    name: greeting-server-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service: 
  greeting: "Pronto"
  default-value: "Mondo"
